/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UtilesMecanico.UtilesMecanico;
import ControladorDao.MantenerCesion;
import Modelo.Persona;
import Modelo.Servicio;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Cris2
 */
public class Frm_Mecanico extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Mecanico
     */
    Panel_RegistroVehiculo PRVehiculo = new Panel_RegistroVehiculo();
    Panel_RegistroCliente PRCliente = new Panel_RegistroCliente();
    Panel_EditarCliente PRECliente=new Panel_EditarCliente();
    Panel_EditarVehiculo PREVehiculo=new Panel_EditarVehiculo();
    Panel_OrdenReparacion POrden=new Panel_OrdenReparacion();
    Panel_BienvenidaMecanico PBien;
    UtilesMecanico uti=new UtilesMecanico();
    
    public Frm_Mecanico() {
        initComponents();
        cargarFondo();
        ControladorDao.MantenerCesion<Persona> serv=new MantenerCesion<>();
        String nombre=serv.listar("Persona").getNombre()+" "+serv.listar("Persona").getApellido();
        PBien=new Panel_BienvenidaMecanico(nombre);
        PBien.setVisible(true);
        txtNombre.setText(nombre);      
        txtNombre.setIcon(uti.img(serv.listar("Persona").getImagenObtenida(),new Dimension(35, 35)));
        PRVehiculo.setVisible(false);
        PRCliente.setVisible(false);
        PRECliente.setVisible(false);
        PREVehiculo.setVisible(false);
        POrden.setVisible(false);
        PanelContenedor.add(PBien);
        
    }
    /**
     * Metodo encargado de cargar la imagen de fondo del sistema
     */
    public void cargarFondo(){
        int alto=this.getSize().height;
        int ancho=this.getSize().width;
        Image img = getToolkit().getImage(getClass().getResource("/Imagenes/FondoMetalico.jpg"));
        img=img.getScaledInstance(ancho, alto, Image.SCALE_DEFAULT);
        jLabel5.setIcon(new ImageIcon(img));
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(735, 485));
        setResizable(false);
        getContentPane().setLayout(null);

        PanelContenedor.setMinimumSize(new java.awt.Dimension(735, 485));
        PanelContenedor.setOpaque(false);
        PanelContenedor.setPreferredSize(new java.awt.Dimension(735, 485));
        PanelContenedor.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/car-2-add.png"))); // NOI18N
        jButton2.setToolTipText("Registrar vehiculos");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(false);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 35, 35));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga (1).png"))); // NOI18N
        jButton5.setToolTipText("Administrar Vehiculos");
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setOpaque(false);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 35, 35));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon.png"))); // NOI18N
        jButton6.setToolTipText("Orden de reparacion");
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setOpaque(false);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 35, 35));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20699.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setOpaque(false);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 35, 35));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modCliente.png"))); // NOI18N
        jButton4.setToolTipText("Administrar clientes");
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setOpaque(false);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 35, 35));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoVerCliente.png"))); // NOI18N
        jButton3.setToolTipText("Ver clientes");
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setOpaque(false);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 35, 35));

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clienteNuevos.png"))); // NOI18N
        btnAgregarCliente.setToolTipText("Registrar clientes");
        btnAgregarCliente.setContentAreaFilled(false);
        btnAgregarCliente.setOpaque(false);
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 35, 35));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setContentAreaFilled(false);
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setOpaque(false);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 35));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 2, 20, 30));

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 210, 35));

        PanelContenedor.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(PanelContenedor);
        PanelContenedor.setBounds(0, 0, 735, 485);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 730, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PRCliente.setVisible(false);
        PRVehiculo.setVisible(false);
        PRECliente.setVisible(true);
        PREVehiculo.setVisible(false);
        POrden.setVisible(false);
        PBien.setVisible(false);
        PanelContenedor.add(PRECliente);
        PRECliente.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        PRCliente.setVisible(true);
        PRVehiculo.setVisible(false);
        PRECliente.setVisible(false);
        PREVehiculo.setVisible(false);
        POrden.setVisible(false);
        PBien.setVisible(false);
        PanelContenedor.add(PRCliente);
        PRCliente.validate();    // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PRCliente.setVisible(false);
        PRVehiculo.setVisible(false);
        PRECliente.setVisible(false);
        PREVehiculo.setVisible(false);
        POrden.setVisible(true);
        PBien.setVisible(false);
        PanelContenedor.add(POrden);
        POrden.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        PRCliente.setVisible(false);
        PRVehiculo.setVisible(false);
        PRECliente.setVisible(false);
        PREVehiculo.setVisible(true);
        POrden.setVisible(false);
        PBien.setVisible(false);
        PanelContenedor.add(PREVehiculo);
        PREVehiculo.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PRCliente.setVisible(false);
        PRVehiculo.setVisible(true);
        PRECliente.setVisible(false);
        PREVehiculo.setVisible(false);
        POrden.setVisible(false);
        PBien.setVisible(false);
        PanelContenedor.add(PRVehiculo);
        PRVehiculo.validate();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        PRCliente.setVisible(false);
        PRVehiculo.setVisible(false);
        PRECliente.setVisible(false);
        PREVehiculo.setVisible(false);
        POrden.setVisible(false);
        PBien.setVisible(true); 
        PanelContenedor.add(PBien);
        PBien.validate();// TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Mecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Mecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
