/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.UtilesMecanico.UtilesMecanico;
import java.awt.Image;
import java.io.File;
import javax.naming.spi.DirectoryManager;
import javax.swing.ImageIcon;

/**
 *
 * @author Cris2
 */
public class Panel_BienvenidaMecanico extends javax.swing.JPanel {

    /**
     * Creates new form Pane_BienvenidaMecanico
     */
    UtilesMecanico uti=new UtilesMecanico();
    /**
     * String nombre controlador
     * @param nombre String
     */
    public Panel_BienvenidaMecanico(String nombre) {
        initComponents();
        int alto=jLabel2.getSize().height;
        int ancho=jLabel2.getSize().width;
        File[] files=uti.traerDirectorio();
        ImageIcon[] iconos=new ImageIcon[files.length];
        for (int i = 0; i <files.length ; i++) {
            Image foto = getToolkit().getImage(String.valueOf(files[i]));
            foto = foto.getScaledInstance(ancho, alto, Image.SCALE_DEFAULT);
            iconos[i]=new ImageIcon(foto);
        }
        uti.retardo(jLabel2,inf, iconos);
        txtNombre.setText(nombre);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(txtNombre);
        txtNombre.setBounds(120, 90, 460, 30);

        jPanel1.setLayout(null);

        inf.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jPanel1.add(inf);
        inf.setBounds(190, 237, 270, 10);

        jLabel2.setBackground(new java.awt.Color(102, 255, 102));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 463, 248);

        add(jPanel1);
        jPanel1.setBounds(120, 120, 460, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Titulo.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(120, 10, 460, 110);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel inf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
