/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorOrdenReparacion;
import Controlador.ControladorVehiculo;
import Controlador.UtilesMecanico.UtilesMecanico;
import java.awt.Color;
import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cris2
 */
public class Panel_OrdenReparacion extends javax.swing.JPanel {

    /** Creates new form Panel_OrdenReparacion */
    DefaultTableModel modelo;
    ControladorVehiculo ctr = new ControladorVehiculo();
    ControladorOrdenReparacion ctr1=new ControladorOrdenReparacion();
    UtilesMecanico uti = new UtilesMecanico();
    File file = null;
    String ColorRGB;
    Long idLong = null;
    public Panel_OrdenReparacion() {
        initComponents();
        uti.IniciarConexion();
        modelo = (DefaultTableModel) Tabla1.getModel();
        Tabla1.setModel(modelo);
        if (this.isVisible()) {
            ctr.llenarTablaVehiculo(modelo);
            Tabla1.updateUI();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txtPlaca = new javax.swing.JLabel();
        txtModelo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRequerimiento = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(61, 61, 61));
        setLayout(null);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Propietario", "Cedula"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tabla1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        add(jScrollPane1);
        jScrollPane1.setBounds(360, 130, 350, 240);
        add(txtBuscar);
        txtBuscar.setBounds(360, 90, 230, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Orden de reparacion");
        add(jLabel3);
        jLabel3.setBounds(180, 0, 290, 30);

        jLabel6.setBackground(new java.awt.Color(255, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRayas.jpg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 620, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoRayas.jpg"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(620, 0, 120, 30);

        jLabel1.setBackground(new java.awt.Color(255, 175, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(590, 90, 70, 30);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 153, 0));
        jCheckBox3.setText("Todo");
        jCheckBox3.setOpaque(false);
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseReleased(evt);
            }
        });
        add(jCheckBox3);
        jCheckBox3.setBounds(530, 50, 80, 30);

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 153, 0));
        jCheckBox2.setText("Placa");
        jCheckBox2.setOpaque(false);
        add(jCheckBox2);
        jCheckBox2.setBounds(440, 50, 80, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 153, 0));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Cedula");
        jCheckBox1.setOpaque(false);
        add(jCheckBox1);
        jCheckBox1.setBounds(360, 50, 80, 30);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(241, 370, 90, 30);

        txtPlaca.setBackground(new java.awt.Color(102, 102, 102));
        txtPlaca.setForeground(new java.awt.Color(255, 255, 255));
        txtPlaca.setOpaque(true);
        add(txtPlaca);
        txtPlaca.setBounds(30, 100, 303, 30);

        txtModelo.setBackground(new java.awt.Color(102, 102, 102));
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));
        txtModelo.setOpaque(true);
        add(txtModelo);
        txtModelo.setBounds(30, 140, 303, 29);

        txtNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setOpaque(true);
        add(txtNombre);
        txtNombre.setBounds(30, 180, 303, 29);

        txtCedula.setBackground(new java.awt.Color(102, 102, 102));
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setOpaque(true);
        add(txtCedula);
        txtCedula.setBounds(30, 220, 303, 29);

        txtRequerimiento.setColumns(20);
        txtRequerimiento.setRows(5);
        jScrollPane2.setViewportView(txtRequerimiento);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 260, 300, 96);

        jLabel2.setBackground(new java.awt.Color(61, 61, 61));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMetalico.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 730, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseReleased
        System.out.println("Selecciono: " + (Tabla1.getSelectedRow()) + "Tamaño: " + Tabla1.getRowCount());
        String a = Tabla1.getValueAt(Tabla1.getSelectedRow(), 0).toString();
        System.out.println("a: " + a);
        RefrescarDatos(a);        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        try {
            if (jCheckBox1.isSelected()) {
                ctr.buscarPersona(String.valueOf(txtBuscar.getText()));
                if (ctr.getPaux() != null) {
                    ctr.llenarTablaBusquedaVehiculo(modelo, ctr.getPaux());
                    Tabla1.updateUI();
                }
            } else {
                ctr.llenarTablaFiltrarPlaca(ctr.BuscarPlaca(txtBuscar.getText()), modelo);
                Tabla1.updateUI();
            }
        } catch (NumberFormatException e) {
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void jCheckBox3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseReleased
        if (jCheckBox3.isSelected()) {
            ctr.llenarTablaVehiculo(modelo);
            Tabla1.updateUI();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ctr1.Registrar(txtRequerimiento.getText(), ctr.getVaux().getId());
        ctr1.GuardarOrden();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    private void RefrescarDatos(String placa) {
        ctr.recuperarDatosMod();
        ctr.llenartxt(placa);
        ctr.buscarModeloVehiculo(String.valueOf(ctr.getVaux().getIdModeloVehiculo()));
        ctr.buscarPersona(String.valueOf(ctr.getVaux().getIdPersona()));
        txtModelo.setText(ctr.getMaux().getNombreModelo());
        txtPlaca.setText(ctr.getVaux().getPlaca());
        txtNombre.setText(ctr.getPaux().getNombre()+" "+ctr.getPaux().getApellido());
        txtCedula.setText(ctr.getPaux().getCedula());
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JTextArea txtRequerimiento;
    // End of variables declaration//GEN-END:variables

}
