/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCliente;
import Controlador.ControladorCuenta;
import Controlador.ControladorVehiculo;
import Controlador.UtilesMecanico.UtilesMecanico;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cris2
 */
public class Panel_EditarCliente extends javax.swing.JPanel {

    /**
     * Creates new form Panel_EditarCliente
     */
    DefaultTableModel modelo;
    ControladorCliente ctr=new ControladorCliente();
    UtilesMecanico uti=new UtilesMecanico();
    public Panel_EditarCliente() {
        initComponents();
        modelo = (DefaultTableModel) Tabla1.getModel();
        Tabla1.setModel(modelo);
        Noeditar();
        if (this.isVisible()) {
            ctr.llenarTabla(modelo);
            Tabla1.updateUI();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        imagen = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        bxActivo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        btnBuscarImagen = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setLayout(null);

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tabla1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 66, 380, 343);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Cedula");
        add(jCheckBox1);
        jCheckBox1.setBounds(10, 18, 59, 30);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("Apellido");
        add(jCheckBox2);
        jCheckBox2.setBounds(87, 18, 63, 30);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(null);

        txtNombre.setBackground(new java.awt.Color(255, 175, 0));
        txtNombre.setOpaque(true);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(115, 11, 183, 29);

        txtCedula.setBackground(new java.awt.Color(255, 175, 0));
        txtCedula.setOpaque(true);
        jPanel1.add(txtCedula);
        txtCedula.setBounds(115, 46, 183, 29);

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(255, 175, 0));
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(50, 150, 250, 28);

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 175, 0));
        txtTelefono.setBorder(null);
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(50, 190, 250, 28);

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(255, 175, 0));
        txtDireccion.setBorder(null);
        jPanel1.add(txtDireccion);
        txtDireccion.setBounds(50, 230, 250, 28);

        imagen.setOpaque(true);
        jPanel1.add(imagen);
        imagen.setBounds(10, 11, 87, 107);

        btnEditar.setBackground(new java.awt.Color(255, 204, 0));
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditar.setText("Editar");
        btnEditar.setOpaque(true);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(240, 310, 60, 20);

        bxActivo.setBackground(new java.awt.Color(255, 204, 0));
        bxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        bxActivo.setEnabled(false);
        jPanel1.add(bxActivo);
        bxActivo.setBounds(210, 270, 90, 30);

        btnGuardar.setBackground(new java.awt.Color(255, 204, 0));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("Guardar");
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(240, 310, 60, 20);

        btnCancelar.setBackground(new java.awt.Color(255, 204, 0));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setOpaque(true);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(160, 310, 60, 20);

        btnBuscarImagen.setBackground(new java.awt.Color(255, 204, 0));
        btnBuscarImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarImagen.setText("Buscar");
        btnBuscarImagen.setOpaque(true);
        btnBuscarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarImagenMousePressed(evt);
            }
        });
        jPanel1.add(btnBuscarImagen);
        btnBuscarImagen.setBounds(10, 120, 87, 20);

        add(jPanel1);
        jPanel1.setBounds(408, 66, 310, 340);
        add(txtBuscar);
        txtBuscar.setBounds(160, 20, 230, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseReleased
        System.out.println("Selecciono: "+(Tabla1.getSelectedRow())+ "Tamaño: "+Tabla1.getRowCount());
        Noeditar();
        String a = Tabla1.getValueAt(Tabla1.getSelectedRow(), 2).toString();
        System.out.println("a: "+a);
        RefrescarDatos(a);
        
// TODO add your handling code here:
    }//GEN-LAST:event_Tabla1MouseReleased
    private void RefrescarDatos(String cedula){
        ctr.cliente(cedula);
        txtNombre.setText(ctr.getPersona().getNombre()+" "+ctr.getPersona().getApellido());
        txtCedula.setText(ctr.getPersona().getCedula()); 
        txtCorreo.setText(ctr.getPersona().getCorreo());
        txtTelefono.setText(ctr.getPersona().getTelefono());
        txtDireccion.setText(ctr.getPersona().getDireccion());
        imagen.setIcon(uti.img(ctr.getPersona().getImagenObtenida(),imagen.getSize()));
        if (ctr.getPersona().getEstado().booleanValue()) {
            bxActivo.setSelectedItem("Activo");
        }else{
            bxActivo.setSelectedItem("Inactivo");
        }
    }
    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        editar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMousePressed

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        ctr.Editar(txtCorreo.getText(), txtTelefono.getText(), txtDireccion.getText(), txtCedula.getText());
        Noeditar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMousePressed

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        Noeditar();
        RefrescarDatos(txtCedula.getText());// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMousePressed

    private void btnBuscarImagenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarImagenMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarImagenMousePressed
    public void editar(){
        btnGuardar.setVisible(true);
        btnCancelar.setVisible(true);
        btnEditar.setVisible(false);
        btnBuscarImagen.setVisible(true);
        txtCorreo.setEditable(true);
        txtTelefono.setEditable(true);
        txtDireccion.setEditable(true);
        bxActivo.setEnabled(true);
        txtCorreo.setBackground(Color.white);
        txtTelefono.setBackground(Color.white);
        txtDireccion.setBackground(Color.white);
        
                
    }
    public void Noeditar(){
        btnEditar.setVisible(true);
        btnGuardar.setVisible(false);
        btnCancelar.setVisible(false);
        btnBuscarImagen.setVisible(false);
        txtCorreo.setEditable(false);
        txtTelefono.setEditable(false);
        txtDireccion.setEditable(false);
        bxActivo.setEnabled(false);
        txtCorreo.setBackground(new Color(255,175,0));
        txtTelefono.setBackground(new Color(255,175,0));
        txtDireccion.setBackground(new Color(255,175,0));
                
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JLabel btnBuscarImagen;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> bxActivo;
    private javax.swing.JLabel imagen;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
